AWSTemplateFormatVersion: 2010-09-09
Description: treasury infrastructure setup

Parameters:
  Stage:
    Description: Stage of the application
    Type: String
  ServiceName:
    Description: The name of the application to roll out
    Type: String
  EC2Id:
    Description: Instance Id of the application
    Type: "String"

Resources:

  EC2PasswordSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      GenerateSecretString:
        SecretStringTemplate: !Join ['', ['{"username": "', "Administrator", '"}']]
        GenerateStringKey: "password"
        ExcludePunctuation: true
        PasswordLength: 16
      Tags:
        - Key: instanceid
          Value: !Ref EC2Id
        - Key: cov:leg-access
          Value: appl 
  RotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    DependsOn: LambdaPermissions
    Properties: 
      RotationLambdaARN: !GetAtt RotatePassword.Arn
      RotationRules: 
        AutomaticallyAfterDays: 90
      SecretId: !Ref EC2PasswordSecret


  RotatePassword:
    Type: AWS::Lambda::Function
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W3002
    Properties:
      Description: Function to rotate password of windows instance
      Code: "lambda/password-rotation/"
      FunctionName: !Sub "ec2-password-rotation-${ServiceName}-${Stage}"
      Role: !GetAtt ExecutionRole.Arn
      Runtime: python3.8
      Handler: main.lambda_handler
      Timeout: 60

  LambdaPermissions:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt RotatePassword.Arn
      Principal: 'secretsmanager.amazonaws.com'

  ExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
        - "arn:aws:iam::aws:policy/AmazonSSMFullAccess"
      Policies:
        - PolicyName: SecretsManagerPermissions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                - "secretsmanager:DescribeSecret"
                - "secretsmanager:GetSecretValue"
                - "secretsmanager:PutSecretValue"
                - "secretsmanager:UpdateSecretVersionStage"
                - "secretsmanager:GetRandomPassword"
                Resource: '*'
              - Effect: Allow
                Action:
                - "ec2:DescribeInstances"
                Resource: '*'