AWSTemplateFormatVersion: 2010-09-09
Description: iims SES setup

Parameters:
  Stage:
    Description: Environment name, dev/prod
    Type: "String"

  ServiceName:
    Description: The name of the application to roll out
    Type: String

  AdVersionName:
    Description: Version of the SES product
    Type: String
    Default: v0.0.16

Resources:
  ADJoin:
    Type: "AWS::ServiceCatalog::CloudFormationProvisionedProduct"
    Properties:
      ProductId: "prod-xdm3hknc3rc2m"
      ProvisionedProductName: !Sub "${ServiceName}-ADJoin-${Stage}"
      ProvisioningArtifactName: !Ref AdVersionName